### ISSUE TITLE
Add jflory7 to docker group

### ISSUE THREAD

**Issue by Tjzabel** [jwflory/conf#5]
When using docker, the user needs to be in the `docker` group, or else `sudo` will need to preface docker commands.

[Here](https://github.com/jwflory/conf/blob/bd21d487e69d5cf1decdcc5deeb6b901f865d8a0/ansible/fedora/setup_fedora.yml#L152) is where the groups are assigned to the `jflory7` user.

**Comment by jwflory** [comment]
@Tjzabel Thanks for catching this. I was doing this originally, but the Docker group wasn't created on the installation of the Docker package. So whenever Ansible tried to add me to the group, the task would fail because the group didn't exist.

I put it off because I wanted to double-check if Docker had a direct way of creating the group automatically on install. If not, then I could add a new task to create a Docker group immediately before creating my user account. I'll try to look into this closer. Thanks for filing an issue to help me keep tabs of this. :smile:

**Comment by Tjzabel** [comment]
No problem! You might have to create the docker group first, not sure if it is created when docker is installed. 

Off the top of my head, I'm not sure if `usermod -a -G docker <user>` creates the group if it is not available, or if it has to already exist beforehand.

**Comment by jwflory** [comment]
Closed via 6103dc781139f739be148014fccc54de548465a1. Verified and tested locally in Vagrant VM.
